name: "Deploy frontend to firebase"

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: install dependecies
      run: npm install

    - name: build frontend
      run: npm run build

    # - name: Deploy to Firebase
    #   uses: firebase/firebase-cli@v8
    #   with:
    #     command: deploy
    #     project: "your-project-id"
    #     token: "${{ secrets.FIREBASE_TOKEN }}"
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
